{"name": "test_show_order_with_valid_id", "status": "broken", "statusDetails": {"message": "NameError: name 'URL' is not defined", "trace": "tests_order.py:24: in test_show_order_with_valid_id\n    response = requests.get(f'{URL}{TRACK}', params=payload)\nE   NameError: name 'URL' is not defined\n        payload    = {'t': '767858'}\n        self       = <tests.orders.tests_order.TestPostOrders object at 0x0000018CA3CD4170>"}, "start": 1717162363311, "stop": 1717162363311, "uuid": "5eea1996-c72a-4683-bdcf-6a7424d284a8", "historyId": "a0f5eda28efeb7924ea2846d9a60ebc1", "testCaseId": "a0f5eda28efeb7924ea2846d9a60ebc1", "fullName": "tests.orders.tests_order.TestPostOrders#test_show_order_with_valid_id", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "tests_order"}, {"name": "subSuite", "value": "TestPostOrders"}, {"name": "host", "value": "DESKTOP-N6OG843"}, {"name": "thread", "value": "3732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.tests_order"}]}